Move static apps from src to public due to error
Error:

The Broccoli Plugin: [ResolutionMapBuilder] failed with:
Error: The type of module 'api/app-3cd1a70b082a35972848d2d85c753b39' could not be identified